### 1. Don't have Admin role -> Expect 403 Forbidden
GET http://localhost:4004/odata/v4/admin/OrdersAudit
Accept: application/json


### 2. Have Admin role -> Expect 200 OK
GET http://localhost:4004/odata/v4/admin/OrdersAudit
Accept: application/json
Authorization: Basic YWRtaW46QWRtaW4=


### 3. Try to create new audit record -> Expect 201 Created
POST http://localhost:4004/odata/v4/admin/OrdersAudit
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4=

{
  "customer": "Should Fail",
  "total": 999.99
}
